// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6eigIqy1nW2LbaecpmNgV8WEISbtNdY',
    appId: '1:821605393293:web:4c38f9093c3c0063afd3c4',
    messagingSenderId: '821605393293',
    projectId: 'nerdchat-flutter-mini-chat',
    authDomain: 'nerdchat-flutter-mini-chat.firebaseapp.com',
    storageBucket: 'nerdchat-flutter-mini-chat.appspot.com',
    measurementId: 'G-L08K68HK82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOts_FzeZ91xLGEhXBKYxxiViYYkg9bWY',
    appId: '1:821605393293:android:8527530b572583aeafd3c4',
    messagingSenderId: '821605393293',
    projectId: 'nerdchat-flutter-mini-chat',
    storageBucket: 'nerdchat-flutter-mini-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKyGSXaUskZ2cce6oFtsUYMiu4a44mgc',
    appId: '1:821605393293:ios:b5c7f6e0610959d7afd3c4',
    messagingSenderId: '821605393293',
    projectId: 'nerdchat-flutter-mini-chat',
    storageBucket: 'nerdchat-flutter-mini-chat.appspot.com',
    iosClientId: '821605393293-vu0jhl8456ce7nfmebn9hfcsip0oo2k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniChatAppFlutter',
  );
}
